name: A workflow for my Hello World file
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    container:
      image: python:2.7-stretch
      credentials:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - name: 'execute test script'
        run: python --version
#       - uses: ./action-a
#         with:
#           MY_NAME: "Mona"
