name: A workflow for my Hello World file
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.x', '3.x' ]
    name: Python ${{ matrix.python-version }} sample    
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: 'execute test script'
        run: python --version
#       - uses: ./action-a
#         with:
#           MY_NAME: "Mona"
